# Generated by Django 5.0.4 on 2024-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlongs',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlongs',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlongs',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
